import { MenuItem, Table, Reservation } from "./types";

export const mockMenuItems: MenuItem[] = [
  // Smash Burgers
  {
    id: "s1",
    name: "The OG Double Smash",
    description: "Doppio patty Black Angus smashed sottile e croccante, doppio American cheddar fuso, cetriolini pickles, cipolla tritata e salsa segreta Smash Up in potato bun tostato.",
    price: 9.50,
    category: "primi", // Used for smash burgers
    available: true,
    featured: true,
  },
  {
    id: "s2",
    name: "Bacon Beast Smash",
    description: "Doppio Black Angus smashed con crosticina dorata, triplo bacon croccante al miele, doppio cheddar, cipolla caramellata e salsa BBQ affumicata.",
    price: 11.00,
    category: "primi",
    available: true,
    featured: true,
  },
  {
    id: "s3",
    name: "Truffle & Crispy",
    description: "Doppio patty smashed, provola affumicata campana fusa alla piastra, crema di tartufo nero estivo, cipolla fritta croccante e maionese al pepe nero.",
    price: 12.50,
    category: "primi",
    available: true,
    featured: true,
  },
  {
    id: "s4",
    name: "Spicy Diablo Smash 🌶️",
    description: "Doppio Black Angus, formaggio Pepper Jack piccante, jalapeños croccanti, bacon glassato all'hot honey e maionese alla 'nduja calabrese.",
    price: 11.50,
    category: "primi",
    available: true,
    featured: false,
  },
  {
    id: "s5",
    name: "Triple Monster Smash (270g)",
    description: "Tre patty Black Angus da 90g schiacciati al massimo, triplo cheddar fuso, doppio bacon, cetriolini e doppia salsa della casa.",
    price: 13.50,
    category: "primi",
    available: true,
    featured: false,
  },

  // Crispy Fried Chicken & Starters
  {
    id: "a1",
    name: "Nashville Hot Chicken Bun",
    description: "Coscia di pollo marinata nel latticello per 24h, panatura extra crunchy con spezie Nashville, coleslaw fresca, pickles e maionese al miele piccante.",
    price: 10.50,
    category: "antipasti",
    available: true,
    featured: true,
  },
  {
    id: "a2",
    name: "Crispy Chicken Tenders (5pz)",
    description: "Filetti di pollo fresco con doppia impanatura croccante ai cornflakes, serviti con salsa ranch e salsa barbecue artigianale.",
    price: 6.50,
    category: "antipasti",
    available: true,
    featured: false,
  },
  {
    id: "a3",
    name: "Beer Battered Onion Rings (8pz)",
    description: "Anelli di cipolla interi dorati e pastellati alla birra artigianale, serviti caldi e croccantissimi con salsa smash.",
    price: 5.00,
    category: "antipasti",
    available: true,
    featured: false,
  },
  {
    id: "a4",
    name: "Mozzarella Sticks Filanti (6pz)",
    description: "Bastoncini di vera mozzarella campana dorati all'esterno e morbidamente filanti all'interno con salsa al pomodoro e origano.",
    price: 5.50,
    category: "antipasti",
    available: true,
    featured: false,
  },

  // Loaded Fries
  {
    id: "sec1",
    name: "Smash Loaded Fries 🍟",
    description: "Patatine fritte con la buccia dorate e croccanti, colata di formaggio cheddar caldo fuso, crumble di bacon croccante e salsa smash.",
    price: 6.50,
    category: "secondi",
    available: true,
    featured: true,
  },
  {
    id: "sec2",
    name: "Truffle & Parmesan Fries",
    description: "Patatine fritte speziate con fonduta tiepida di Parmigiano Reggiano 24 mesi e gocce di olio al tartufo nero pregiato.",
    price: 7.00,
    category: "secondi",
    available: true,
    featured: false,
  },
  {
    id: "sec3",
    name: "Diablo Spicy Fries 🌶️",
    description: "Patatine croccanti con polvere di peperoncino affumicato, jalapeños a rondelle, cheddar fuso e maionese piccante.",
    price: 6.50,
    category: "secondi",
    available: true,
    featured: false,
  },
  {
    id: "sec4",
    name: "Classic Skin-On Fries",
    description: "Porzione classica di patatine fritte dorate con sale marino di Cervia e mix di spezie Smash Up.",
    price: 4.00,
    category: "secondi",
    available: true,
    featured: false,
  },

  // Sweets & Drinks
  {
    id: "d1",
    name: "Sweet Smash Bun Nutella & Oreo",
    description: "Potato bun tostato al burro, farcito con abbondante Nutella calda colante e granella croccante di biscotti Oreo.",
    price: 5.50,
    category: "dolci",
    available: true,
    featured: true,
  },
  {
    id: "d2",
    name: "Pistachio Bomb Bun",
    description: "Bun dolce tostato e ripieno di crema vellutata al pistacchio di Bronte pura, gocce di cioccolato bianco e granella.",
    price: 6.00,
    category: "dolci",
    available: true,
    featured: true,
  },
  {
    id: "d3",
    name: "Cheesecake New York Style",
    description: "La classica torta al formaggio newyorkese con base biscottata al burro e coulis ai frutti di bosco o caramello salato.",
    price: 5.50,
    category: "dolci",
    available: true,
    featured: false,
  },
  {
    id: "d4",
    name: "Birre Artigianali IPA / Blonde",
    description: "Selezione di birre artigianali alla spina e in lattina, perfette in abbinamento con il nostro smash burger.",
    price: 5.00,
    category: "dolci",
    available: true,
    featured: false,
  },
];

export const mockTables: Table[] = [
  { id: "1", number: 1, seats: 2, zone: "sala", position_x: 15, position_y: 20, active: true },
  { id: "2", number: 2, seats: 2, zone: "sala", position_x: 35, position_y: 20, active: true },
  { id: "3", number: 3, seats: 4, zone: "sala", position_x: 60, position_y: 20, active: true },
  { id: "4", number: 4, seats: 4, zone: "sala", position_x: 80, position_y: 20, active: true },
  { id: "5", number: 5, seats: 4, zone: "sala", position_x: 20, position_y: 60, active: true },
  { id: "6", number: 6, seats: 6, zone: "sala", position_x: 50, position_y: 60, active: true },
  { id: "7", number: 7, seats: 6, zone: "esterno", position_x: 80, position_y: 60, active: true },
  { id: "8", number: 8, seats: 8, zone: "esterno", position_x: 25, position_y: 85, active: true },
  { id: "9", number: 9, seats: 4, zone: "sala", position_x: 60, position_y: 85, active: true },
  { id: "10", number: 10, seats: 2, zone: "esterno", position_x: 85, position_y: 85, active: true },
];

export const mockReservationsData: Reservation[] = [
  {
    id: "1",
    name: "Marco Esposito",
    phone: "+39 333 123 4567",
    email: "marco.esposito@email.it",
    guests: 4,
    date: "2026-08-25",
    time: "20:30",
    notes: "Tavolo vicino alla piastra se possibile",
    table_id: "3",
    handled: true,
    status: "confirmed",
    source: "website",
    booking_flow: "inbox",
    response_token: null,
    responded_at: null,
    created_at: "2026-08-25T14:00:00Z",
  },
];
